// Jenkinsfile
pipeline {
    agent any

    triggers {
        scm 'H/1 * * * *'
    }

    stages {
        stage('Build') {
            steps {
                sh 'gradle build'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
        stage('Deploy') {
            steps {
                // Using GCS instead of S3; ensure GCP credentials are available in the runner
                sh 'gsutil cp build/libs/helloworld-1.0-SNAPSHOT.jar gs://sample-bucket/' }
            }
        }
    }
}