pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t sample-web-app .'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh 'docker tag sample-web-app $DOCKER_HUB_USERNAME/sample-web-app'
                sh 'docker push $DOCKER_HUB_USERNAME/sample-web-app'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                kubernetesDeploy(
                    configs: 'deployment.yaml',
                    enableConfigSubstitution: true
                )
            }
        }
    }
}